name: Deploy Backend to Fly.io

on:
  push:
    branches:
      - main
    paths:
      - 'server/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Fly CLI
        run: curl -L https://fly.io/install.sh | sh
      - name: Deploy to Fly.io
        run: fly deploy --remote-only
